# Generated by Django 5.2.10 on 2026-02-12 12:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='preferences', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('dashboard', models.JSONField(blank=True, default=dict, help_text='Dashboard layout and widget configuration.')),
                ('map_config', models.JSONField(blank=True, default=dict, help_text='Map center, zoom, visible layers, etc.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'User preferences',
            },
        ),
    ]
