# Generated by Django 5.2.10 on 2026-02-13 08:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_organizationsettings_allowed_layers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiberAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fiber_id', models.CharField(help_text='Matches fiber_cables.fiber_id in ClickHouse.', max_length=100)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiber_assignments', to='organizations.organization')),
            ],
            options={
                'ordering': ['organization', 'fiber_id'],
                'unique_together': {('organization', 'fiber_id')},
            },
        ),
    ]
