# Generated by Django 5.2.10 on 2026-03-25 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fibers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FiberCable",
            fields=[
                (
                    "id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=200)),
                ("color", models.CharField(default="#000000", max_length=20)),
                (
                    "coordinates",
                    models.JSONField(
                        default=list, help_text="Per-channel [lng, lat] coordinates."
                    ),
                ),
                (
                    "directional_paths",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Direction-specific coordinates for map rendering.",
                    ),
                ),
                (
                    "landmark_labels",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Landmark name per channel index (empty string = no landmark).",
                    ),
                ),
                ("lanes", models.IntegerField(default=4)),
                (
                    "speed_limit",
                    models.IntegerField(
                        default=50, help_text="Road speed limit in km/h."
                    ),
                ),
                (
                    "traffic_density",
                    models.CharField(
                        default="medium",
                        help_text="Traffic density: low, medium, high.",
                        max_length=20,
                    ),
                ),
                (
                    "typical_speed_min",
                    models.FloatField(
                        default=30.0,
                        help_text="Typical free-flow speed range minimum (km/h).",
                    ),
                ),
                (
                    "typical_speed_max",
                    models.FloatField(
                        default=50.0,
                        help_text="Typical free-flow speed range maximum (km/h).",
                    ),
                ),
                (
                    "max_channel_dir0",
                    models.IntegerField(
                        blank=True,
                        help_text="Last valid channel for direction 0 (null = full fiber).",
                        null=True,
                    ),
                ),
                (
                    "max_channel_dir1",
                    models.IntegerField(
                        blank=True,
                        help_text="Last valid channel for direction 1 (null = full fiber).",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Fiber cables",
                "ordering": ["name"],
            },
        ),
        migrations.AlterField(
            model_name="fiberassignment",
            name="fiber_id",
            field=models.CharField(help_text="Matches FiberCable.id.", max_length=100),
        ),
    ]
