# Generated by Django 5.2.10 on 2026-03-25 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fibers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FiberCable",
            fields=[
                (
                    "id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=200)),
                ("color", models.CharField(default="#000000", max_length=20)),
                (
                    "coordinates",
                    models.JSONField(
                        default=list, help_text="Per-channel [lng, lat] coordinates."
                    ),
                ),
                (
                    "directional_paths",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Direction-specific coordinates for map rendering.",
                    ),
                ),
                (
                    "landmark_labels",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Landmark name per channel index (empty string = no landmark).",
                    ),
                ),
                (
                    "channel_count",
                    models.IntegerField(
                        default=0,
                        help_text="Number of DAS channels (= len(coordinates)).",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Fiber cables",
                "ordering": ["name"],
            },
        ),
        migrations.AlterField(
            model_name="fiberassignment",
            name="fiber_id",
            field=models.CharField(help_text="Matches FiberCable.id.", max_length=100),
        ),
    ]
