# Generated by Django 5.2.10 on 2026-03-30 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fibers", "0003_seed_fiber_cables"),
    ]

    operations = [
        migrations.AddField(
            model_name="fibercable",
            name="data_coverage",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='Active channel ranges: [{"start": 1200, "end": 1716}, ...]',
            ),
        ),
    ]
