services:
  platform-backend:
    volumes:
      - ./secrets:/app/secrets:ro
  ai-engine-carros:
    environment:
      - NVIDIA_VISIBLE_DEVICES=1
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['1']
              capabilities: [gpu]
  # ai-engine-mathis:
  #   environment:
  #     - NVIDIA_VISIBLE_DEVICES=1
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #           - driver: nvidia
  #             device_ids: ['1']
  #             capabilities: [gpu]
  # ai-engine-promenade:
  #   environment:
  #     - NVIDIA_VISIBLE_DEVICES=1
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #           - driver: nvidia
  #             device_ids: ['1']
  #             capabilities: [gpu]
  processor-carros:
    volumes:
      - ./data/captures:/app/data_captures:rw
  # processor-mathis:
  #   volumes:
  #     - ./data/captures:/app/data_captures:rw
  # processor-promenade:
  #   volumes:
  #   - ./data/captures:/app/data_captures:rw
