# Generated by Django 5.2.10 on 2026-02-13 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='can_manage_fibers',
        ),
        migrations.RemoveField(
            model_name='user',
            name='can_manage_incidents',
        ),
        migrations.RemoveField(
            model_name='user',
            name='can_manage_settings',
        ),
        migrations.RemoveField(
            model_name='user',
            name='can_manage_users',
        ),
    ]
