"""Golden snapshot tests: change detection for AI engine inference.

These tests run inference on real post-preprocessed DAS data and compare
the output to a saved reference. If output changes (due to model update,
preprocessing change, parameter change), the test fails with a detailed
diagnostic message.

To accept a new baseline after an intentional change:
    make snapshot-confirm

The .npz fixtures are generated by:
    tests/ai_engine/fixtures/generate_golden_fixture.py
"""

from __future__ import annotations

from pathlib import Path

import numpy as np
import pytest
import torch

from ai_engine.model_vehicle.utils import normalize_channel_energy

FIXTURE_DIR = Path(__file__).parent / "fixtures"
GOLDEN_INPUT = FIXTURE_DIR / "golden_input.npz"
GOLDEN_REF = FIXTURE_DIR / "golden_reference.npz"
GOLDEN_NORM = FIXTURE_DIR / "golden_normalization.npz"

_SNAPSHOT_HELP = """
SNAPSHOT MISMATCH -- AI engine golden test

  This test fails when AI engine output changes. This is expected after:
    - Model weight updates (.pth file)
    - Preprocessing changes (normalization, filtering)
    - Detection parameter changes (thresholds, speed bounds)

  To accept the new baseline:
    make snapshot-confirm

  Then commit the updated files in tests/ai_engine/fixtures/
"""

# The golden fixtures use the same model config as conftest.py's session-scoped
# estimator (same exp_name, Nch, fs, gauge, thresholds). We reuse it to avoid
# a 12-second duplicate model load.


def _check_fixtures():
    missing = []
    if not GOLDEN_INPUT.exists():
        missing.append(str(GOLDEN_INPUT))
    if not GOLDEN_REF.exists():
        missing.append(str(GOLDEN_REF))
    if missing:
        raise FileNotFoundError(
            f"Golden fixtures missing: {', '.join(missing)}\n"
            f"Generate with: make snapshot-confirm\n"
            f"Then commit the .npz files."
        )


_check_fixtures()


@pytest.fixture(scope="module")
def golden_input():
    """Load golden input data from .npz fixture."""
    data = np.load(GOLDEN_INPUT)
    return data["data_window"], data["timestamps"], data["timestamps_ns"]


@pytest.fixture(scope="module")
def golden_ref():
    """Load golden reference output from .npz fixture."""
    return np.load(GOLDEN_REF)


@pytest.fixture(scope="module")
def golden_results(estimator, golden_input):
    """Run inference on golden input (cached per module)."""
    data_window, timestamps, timestamps_ns = golden_input
    torch.manual_seed(42)
    results = list(estimator.process_file(data_window, timestamps, timestamps_ns))

    all_detections = []
    for result in results:
        direction = int(result.direction_mask[0, 0])
        detections = estimator.extract_detections(
            glrt_summed=result.glrt_summed,
            aligned_speed_pairs=result.aligned_speed_per_pair,
            direction=direction,
            timestamps_ns=result.timestamps_ns,
            aligned_data=result.aligned_data,
        )
        all_detections.extend(detections)

    return results, all_detections


class TestGoldenSnapshotDetections:
    """Snapshot tests comparing detection output to saved reference."""

    def test_detection_count(self, golden_results, golden_ref):
        """Number of detections must match reference."""
        _, detections = golden_results
        expected_count = int(golden_ref["n_detections"])
        actual_count = len(detections)

        if actual_count != expected_count:
            pytest.fail(
                f"Detection count changed: expected {expected_count}, got {actual_count} "
                f"(delta: {actual_count - expected_count:+d})\n{_SNAPSHOT_HELP}"
            )

    def test_detection_speeds(self, golden_results, golden_ref):
        """Detection speeds must match reference within tolerance."""
        _, detections = golden_results
        if not detections:
            return

        actual_speeds = np.array(sorted(d["speed_kmh"] for d in detections))
        expected_speeds = np.sort(golden_ref["det_speeds"])

        if len(actual_speeds) != len(expected_speeds):
            return  # count test will catch

        speed_diff = np.abs(actual_speeds - expected_speeds)
        max_diff = speed_diff.max()

        if max_diff > 0.5:  # 0.5 km/h tolerance
            pytest.fail(
                f"Detection speeds changed:\n"
                f"  Max difference: {max_diff:.2f} km/h\n"
                f"  Expected range: [{expected_speeds.min():.1f}, {expected_speeds.max():.1f}]\n"
                f"  Actual range:   [{actual_speeds.min():.1f}, {actual_speeds.max():.1f}]\n"
                f"{_SNAPSHOT_HELP}"
            )

    def test_detection_directions(self, golden_results, golden_ref):
        """Forward/reverse detection split must match reference."""
        _, detections = golden_results
        if not detections:
            return

        actual_fwd = sum(1 for d in detections if d["direction"] == 0)
        actual_rev = sum(1 for d in detections if d["direction"] == 1)
        expected_fwd = int(np.sum(golden_ref["det_directions"] == 0))
        expected_rev = int(np.sum(golden_ref["det_directions"] == 1))

        if actual_fwd != expected_fwd or actual_rev != expected_rev:
            pytest.fail(
                f"Direction split changed:\n"
                f"  Expected: fwd={expected_fwd}, rev={expected_rev}\n"
                f"  Actual:   fwd={actual_fwd}, rev={actual_rev}\n"
                f"{_SNAPSHOT_HELP}"
            )

    def test_detection_glrt_range(self, golden_results, golden_ref):
        """GLRT peak range must match reference within tolerance."""
        _, detections = golden_results
        if not detections:
            return

        actual_glrt = np.array(sorted(d["glrt_max"] for d in detections))
        expected_glrt = np.sort(golden_ref["det_glrt_max"])

        if len(actual_glrt) != len(expected_glrt):
            return  # count test will catch

        rel_diff = np.abs(actual_glrt - expected_glrt) / (expected_glrt + 1e-8)
        max_rel = rel_diff.max()

        if max_rel > 0.01:  # 1% relative tolerance
            pytest.fail(f"GLRT peaks changed (max relative diff: {max_rel:.4f})\n{_SNAPSHOT_HELP}")


class TestGoldenSnapshotArrays:
    """Snapshot tests for intermediate array outputs (GLRT, speed)."""

    def test_fwd_glrt_summed(self, golden_results, golden_ref):
        """Forward GLRT summed array must match reference."""
        results, _ = golden_results
        fwd_results = [r for r in results if int(r.direction_mask[0, 0]) == 0]
        if not fwd_results or "fwd_glrt_summed" not in golden_ref:
            return

        actual = fwd_results[0].glrt_summed
        expected = golden_ref["fwd_glrt_summed"]

        if actual.shape != expected.shape:
            pytest.fail(
                f"Forward GLRT shape changed: {expected.shape} -> {actual.shape}\n{_SNAPSHOT_HELP}"
            )

        if np.abs(actual - expected).max() > 1.0:
            pytest.fail(
                f"Forward GLRT values changed (max diff: {np.abs(actual - expected).max():.4f})\n{_SNAPSHOT_HELP}"
            )

    def test_rev_glrt_summed(self, golden_results, golden_ref):
        """Reverse GLRT summed array must match reference."""
        results, _ = golden_results
        rev_results = [r for r in results if int(r.direction_mask[0, 0]) == 1]
        if not rev_results or "rev_glrt_summed" not in golden_ref:
            return

        actual = rev_results[0].glrt_summed
        expected = golden_ref["rev_glrt_summed"]

        if actual.shape != expected.shape:
            pytest.fail(
                f"Reverse GLRT shape changed: {expected.shape} -> {actual.shape}\n{_SNAPSHOT_HELP}"
            )

        if np.abs(actual - expected).max() > 1.0:
            pytest.fail(
                f"Reverse GLRT values changed (max diff: {np.abs(actual - expected).max():.4f})\n{_SNAPSHOT_HELP}"
            )


class TestGoldenNormalization:
    """Snapshot test for preprocessing normalization parity."""

    def test_normalization_matches_reference(self, estimator, golden_input):
        """normalize_channel_energy on golden input must match saved reference."""
        assert GOLDEN_NORM.exists(), f"Normalization fixture missing: {GOLDEN_NORM}"

        data_window, _, _ = golden_input
        ref = np.load(GOLDEN_NORM)
        expected = ref["normalized_first_window"]

        space_split = estimator.split_channel_overlap(data_window)
        actual = normalize_channel_energy(space_split[0])

        np.testing.assert_allclose(
            actual,
            expected,
            rtol=1e-6,
            atol=1e-10,
            err_msg=f"Normalization output changed. This indicates preprocessing drift.\n{_SNAPSHOT_HELP}",
        )


class TestGoldenInvariants:
    """Tests that must always hold regardless of model version.

    These do NOT compare to a snapshot -- they test properties that should
    be true for any valid model on real data.
    """

    def test_all_speeds_in_bounds(self, golden_results):
        """Every detection speed must be within configured [min, max]."""
        _, detections = golden_results
        for det in detections:
            assert 20.0 <= det["speed_kmh"] <= 120.0, (
                f"Detection speed {det['speed_kmh']:.1f} outside [20, 120] bounds"
            )

    def test_all_directions_valid(self, golden_results):
        """Every detection direction must be 0 or 1."""
        _, detections = golden_results
        for det in detections:
            assert det["direction"] in (0, 1)

    def test_all_fields_present(self, golden_results):
        """Every detection must contain all required fields."""
        required = {
            "section_idx",
            "speed_kmh",
            "direction",
            "timestamp_ns",
            "glrt_max",
            "vehicle_count",
            "n_cars",
            "n_trucks",
            "strain_peak",
            "strain_rms",
            "_t_mid_sample",
        }
        _, detections = golden_results
        for det in detections:
            missing = required - set(det.keys())
            assert not missing, f"Detection missing fields: {missing}"

    def test_all_values_finite(self, golden_results):
        """No NaN or Inf in any numeric detection field."""
        _, detections = golden_results
        numeric_fields = [
            "speed_kmh",
            "glrt_max",
            "vehicle_count",
            "n_cars",
            "n_trucks",
            "strain_peak",
            "strain_rms",
        ]
        for det in detections:
            for field in numeric_fields:
                assert np.isfinite(det[field]), f"Non-finite {field}={det[field]}"

    def test_vehicle_count_at_least_one(self, golden_results):
        """Every detection must have vehicle_count >= 1."""
        _, detections = golden_results
        for det in detections:
            assert det["vehicle_count"] >= 1.0

    def test_glrt_positive(self, golden_results):
        """GLRT peak must be positive for every detection."""
        _, detections = golden_results
        for det in detections:
            assert det["glrt_max"] > 0

    def test_real_data_produces_detections(self, golden_results):
        """Real DAS data with known traffic must produce at least some detections."""
        _, detections = golden_results
        assert len(detections) > 0, "Real DAS data produced zero detections."

    def test_both_directions_detected(self, golden_results):
        """Bidirectional detection on a road should find vehicles in both directions."""
        _, detections = golden_results
        directions = {d["direction"] for d in detections}
        assert 0 in directions, "No forward detections on real data"
        assert 1 in directions, "No reverse detections on real data"
