apiVersion: 1

datasources:
  - name: ClickHouse
    type: grafana-clickhouse-datasource
    uid: clickhouse
    access: proxy
    url: http://clickhouse:8123
    jsonData:
      defaultDatabase: sequoia
      port: 9000
      server: clickhouse
      username: grafana_readonly
      tlsSkipVerify: true
    secureJsonData:
      password: ${CLICKHOUSE_GRAFANA_PASSWORD}
    editable: true

  - name: Prometheus
    type: prometheus
    uid: prometheus
    access: proxy
    url: http://localhost:9090
    isDefault: true
    jsonData:
      timeInterval: 15s
    editable: true

  - name: Loki
    type: loki
    uid: loki
    access: proxy
    url: http://localhost:3100
    editable: true

  - name: Tempo
    type: tempo
    uid: tempo
    access: proxy
    url: http://localhost:3200
    editable: true
    jsonData:
      tracesToLogsV2:
        datasourceUid: loki
      tracesToMetrics:
        datasourceUid: prometheus
      serviceMap:
        datasourceUid: prometheus
      nodeGraph:
        enabled: true
