# Generated by Django 5.2.10 on 2026-02-12 12:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('auth.login', 'Login success'), ('auth.login_failed', 'Login failed'), ('auth.password_changed', 'Password changed'), ('user.created', 'User created'), ('user.updated', 'User updated'), ('user.deleted', 'User deleted'), ('role.assigned', 'Role assigned'), ('org.settings_updated', 'Organization settings updated'), ('preferences.updated', 'Preferences updated'), ('incident.updated', 'Incident updated'), ('incident.resolved', 'Incident resolved'), ('infrastructure.updated', 'Infrastructure updated')], db_index=True, max_length=50)),
                ('object_type', models.CharField(blank=True, default='', help_text='The type of object affected (e.g. "User", "Infrastructure").', max_length=50)),
                ('object_id', models.CharField(blank=True, default='', help_text='The ID of the affected object.', max_length=255)),
                ('changes', models.JSONField(blank=True, default=dict, help_text='JSON describing what changed.')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='organizations.organization')),
                ('user', models.ForeignKey(blank=True, help_text='The user who performed the action.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', '-created_at'], name='shared_audi_organiz_4942f7_idx'), models.Index(fields=['user', '-created_at'], name='shared_audi_user_id_3eca40_idx'), models.Index(fields=['action', '-created_at'], name='shared_audi_action_70f7be_idx')],
            },
        ),
    ]
