# Generated by Django 5.2.10 on 2026-04-05 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shared", "0002_alter_auditlog_organization"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("auth.login", "Login success"),
                    ("auth.login_failed", "Login failed"),
                    ("auth.oidc_provisioned", "OIDC user provisioned"),
                    ("user.created", "User created"),
                    ("user.updated", "User updated"),
                    ("user.deleted", "User deleted"),
                    ("role.assigned", "Role assigned"),
                    ("org.settings_updated", "Organization settings updated"),
                    ("preferences.updated", "Preferences updated"),
                    ("incident.updated", "Incident updated"),
                    ("incident.resolved", "Incident resolved"),
                    ("infrastructure.updated", "Infrastructure updated"),
                ],
                db_index=True,
                max_length=50,
            ),
        ),
    ]
