# Generated by Django 5.2.10 on 2026-02-12 12:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timezone', models.CharField(default='Europe/Paris', max_length=50)),
                ('speed_alert_threshold', models.FloatField(default=20.0, help_text='Speed (km/h) below which to flag slowdown alerts.')),
                ('incident_auto_resolve_minutes', models.PositiveIntegerField(default=30, help_text='Auto-resolve incidents after N minutes of no updates.')),
                ('shm_enabled', models.BooleanField(default=True, help_text='Enable structural health monitoring widget.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='organizations.organization')),
            ],
            options={
                'verbose_name_plural': 'Organization settings',
            },
        ),
    ]
