# Generated by Django 5.2.10 on 2026-02-13 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsettings',
            name='allowed_layers',
            field=models.JSONField(blank=True, default=list, help_text='Map layer keys this org can access. Empty = all layers.'),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='allowed_widgets',
            field=models.JSONField(blank=True, default=list, help_text='Widget keys this org can access. Empty = all widgets.'),
        ),
    ]
