# Generated by Django 5.2.10 on 2026-02-28 15:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_organizationsettings_allowed_layers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('rule_type', models.CharField(choices=[('speed_below', 'Speed Below Threshold'), ('incident_type', 'Incident Type Match')], max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('threshold', models.FloatField(blank=True, null=True)),
                ('incident_type_filter', models.JSONField(blank=True, default=list, help_text='List of incident types to match: accident, congestion, anomaly, slowdown')),
                ('severity_filter', models.JSONField(blank=True, default=list, help_text='Only alert for these severities. Empty = all.')),
                ('fiber_id_filter', models.JSONField(blank=True, default=list, help_text='Restrict to these fiber IDs (plain, no direction suffix). Empty = all.')),
                ('channel_start', models.IntegerField(blank=True, null=True)),
                ('channel_end', models.IntegerField(blank=True, null=True)),
                ('dispatch_channel', models.CharField(choices=[('log', 'Log Only'), ('webhook', 'Webhook'), ('email', 'Email')], default='log', max_length=20)),
                ('webhook_url', models.URLField(blank=True, default='')),
                ('email_recipients', models.JSONField(blank=True, default=list, help_text='Email addresses to notify.')),
                ('cooldown_seconds', models.PositiveIntegerField(default=300, help_text='Minimum seconds between alerts from this rule for the same fiber+channel.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to='organizations.organization')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AlertLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('incident_id', models.CharField(blank=True, default='', max_length=100)),
                ('fiber_id', models.CharField(max_length=100)),
                ('channel', models.IntegerField()),
                ('detail', models.TextField(blank=True, default='')),
                ('dispatched_at', models.DateTimeField(auto_now_add=True)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='alerting.alertrule')),
            ],
            options={
                'ordering': ['-dispatched_at'],
                'indexes': [models.Index(fields=['rule', 'fiber_id', 'channel', '-dispatched_at'], name='alerting_al_rule_id_cc26b0_idx')],
            },
        ),
    ]
