# Generated by Django 5.2.10 on 2026-02-12 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Infrastructure',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('bridge', 'Bridge'), ('tunnel', 'Tunnel')], max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('fiber_id', models.CharField(help_text='ID of the fiber cable this infrastructure is on.', max_length=100)),
                ('start_channel', models.IntegerField(help_text='First DAS channel covering this infrastructure.')),
                ('end_channel', models.IntegerField(help_text='Last DAS channel covering this infrastructure.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infrastructure', to='organizations.organization')),
            ],
            options={
                'verbose_name_plural': 'Infrastructure',
                'ordering': ['name'],
            },
        ),
    ]
