# Generated by Django 5.2.10 on 2026-02-17 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='infrastructure',
            name='image',
            field=models.CharField(blank=True, default='', help_text='Filename of infrastructure image (stored in media/infrastructure/).', max_length=255),
        ),
    ]
