# Generated by Django 5.2.10 on 2026-03-08 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0003_incident_action"),
    ]

    operations = [
        migrations.AddField(
            model_name="infrastructure",
            name="direction",
            field=models.IntegerField(
                blank=True,
                help_text="Direction (0 or 1). NULL means both directions.",
                null=True,
            ),
        ),
    ]
