# Generated by Django 5.2.10 on 2026-03-09 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0004_add_direction_to_infrastructure"),
        ("organizations", "0002_organizationsettings_allowed_layers_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("fiber_id", models.CharField(db_index=True, max_length=100)),
                (
                    "direction",
                    models.IntegerField(
                        default=0, help_text="Traffic direction (0 or 1)."
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("channel_start", models.IntegerField()),
                ("channel_end", models.IntegerField()),
                (
                    "expected_travel_time_seconds",
                    models.FloatField(
                        blank=True,
                        help_text="Expected travel time across this section in seconds.",
                        null=True,
                    ),
                ),
                (
                    "alert_threshold_percent",
                    models.FloatField(
                        default=30.0,
                        help_text="Speed drop threshold (%) that triggers an alert.",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_sections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["fiber_id", "channel_start"],
            },
        ),
    ]
