# Generated by Django 5.2.10 on 2026-03-09 15:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0005_section"),
        ("organizations", "0002_organizationsettings_allowed_layers_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="section",
            constraint=models.UniqueConstraint(
                fields=(
                    "organization",
                    "fiber_id",
                    "direction",
                    "channel_start",
                    "channel_end",
                ),
                name="unique_section_range",
            ),
        ),
    ]
