# Generated by Django 5.2.10 on 2026-03-14 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_keys", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="apikey",
            name="request_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
